# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-DublinCore
version:      0.4
version_from: lib/HTML/DublinCore.pm
installdirs:  site
requires:
    DublinCore::Record:            0
    HTML::Parser:                  3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
